### ISSUE TITLE
MP3: I don't want to speak about this

### ISSUE THREAD

**Issue by nicoproto** [sebashrossi/ThePerfectSwing#88]
https://github.com/sebashrossi/ThePerfectSwing/blob/664959a5ac0dbf9aa0e34ab54f417350165eaff9/app/assets/stylesheets/components/_form.scss#L101-L105
![87f8ab4d67b144c0864782392d812c63](https://user-images.githubusercontent.com/43278026/112385376-d5fafc00-8cef-11eb-808b-2d07f7e851d2.gif)

**Comment by sebashrossi** [comment]
HAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHHA
